// <auto-generated />
using HotelBookingConsoleProject.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelBookingConsoleProject.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HotelTypeId");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelTypeId = 1,
                            Name = "Hotel Lux"
                        },
                        new
                        {
                            Id = 2,
                            HotelTypeId = 2,
                            Name = "Economy Stay"
                        },
                        new
                        {
                            Id = 3,
                            HotelTypeId = 3,
                            Name = "Boutique Paradise"
                        },
                        new
                        {
                            Id = 4,
                            HotelTypeId = 4,
                            Name = "Resort Haven"
                        },
                        new
                        {
                            Id = 5,
                            HotelTypeId = 5,
                            Name = "Traveler's Hostel"
                        });
                });

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.HotelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HotelType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Economy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Boutique"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Resort"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hostel"
                        });
                });

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lux Single Room",
                            HotelId = 1,
                            Name = "",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Economy Double Room",
                            HotelId = 2,
                            Name = "",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Boutique Suite",
                            HotelId = 3,
                            Name = "",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Resort Twin Room",
                            HotelId = 4,
                            Name = "",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hostel King Room",
                            HotelId = 5,
                            Name = "",
                            RoomTypeId = 5
                        });
                });

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Twin"
                        },
                        new
                        {
                            Id = 5,
                            Name = "King"
                        });
                });

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.Hotel", b =>
                {
                    b.HasOne("HotelBookingConsoleProject.Domain.Model.Entity.HotelType", "HotelType")
                        .WithMany()
                        .HasForeignKey("HotelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelType");
                });

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.Room", b =>
                {
                    b.HasOne("HotelBookingConsoleProject.Domain.Model.Entity.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelBookingConsoleProject.Domain.Model.Entity.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelBookingConsoleProject.Domain.Model.Entity.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
